services:
  app:
    build: .
    image: langchain_python_sandbox
    container_name: python_sandbox
    command: uvicorn api.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 80:80
    volumes:
      - ./sandbox:/sandbox